### ISSUE TITLE
Add target for iOS

### ISSUE THREAD

**Issue by nathanpbell** [r0fls/swiftstats#1]
Would love to be able to use this in iOS. Could you add a compile target?

**Comment by r0fls** [comment]
@nathanpbell cool you're from PDX too! Anyway, so I didn't do this the correct way (by simply adding a target), but it should work for you. I fiddled with adding a target for way too long considering how easy it is to copy the two files (swiftstats.swift and the unit tests) over to a new cocoa touch framework for iOS and throw it into its own branch. I tested and was able to build and include the `1.0.0-iOS` branch into another project. I might open source that and share it in case you're looking for an example. In any case, here's how you can do it:

1) clone the `1.0.0-iOS` branch
2) create a new iOS project or open an existing one with xcode
3) drag the SwiftStats project into the same workspace in xcode
4) click your main project and choose a target, and add the SwiftStats project
as a `Target Dependency` and to `Link Library With Binaries` (see screenshot for clarity here).

At this point you should be able to import the code into your other swift project as `SwiftStats` and use it normally (as per here: https://github.com/r0fls/swiftstats#example). Let me know if you have any questions or are run into any issues!

![screen shot 2016-12-17 at 4 45 46 pm](https://cloud.githubusercontent.com/assets/1858004/21290676/b11839b4-c478-11e6-84b9-1cff3e744a95.png)

**Comment by rcorty** [comment]
I am not too experienced with swift nor iOS development, so apologies if this is a dumb question.  Why is it beneficial to have an iOS branch separate from the master branch?  It's my understanding that the master branch could have multiple targets.

**Comment by r0fls** [comment]
Ya, it should have a separate target. @rcorty I would love a PR that adds that, if you have time to tackle it. I'm personally more interested in adding more statistical features missing from this library, since I fiddled with adding the target for a couple hours back when this was raised and couldn't get it to work correctly.

**Comment by mattgwwalker** [comment]
Following the blog post "Xcode & cross-platform frameworks" (http://ilya.puchka.me/xcode-cross-platform-frameworks/), I have added an iOS target.

The tricky part was getting the testing to work, as it turns out there's a subtle difference between OSX and iOS in their Runtime search paths.  Resolving that problem took me hours!

This change was branched from the other work I've been doing, so I'll submit a pull request once the earlier changes are accepted.  (I assume you want to review these changes and don't want me to just commit them myself.)

**Comment by r0fls** [comment]
I don’t really mind if you merge your own changes, but it is better practice to have someone else merge them. So, either way. If they’re getting backlogged and you want to merge something yourself, by all means go for it.

**Comment by r0fls** [comment]
Sounds good, though you should be able to happily create multiple separate pull requests if you want to in the future. Just make sure you create the new feature branch from master (sorry formatting, phone doesn’t have the tick character):

git checkout master # get back on master
git checkout -b my-new-feature

Then just do your work on my-new-feature.


This assumes you aren’t merging your branches back into master locally, which you shouldn’t be. Instead you should just periodically update your local master from the upstream master. Let me know if you need more clarification. We could also have this chat via email or on slack if it’s easier.

**Comment by mattgwwalker** [comment]
Thanks for that.  Yes, I wasn't careful enough with the branches I created.  I've never had the opportunity to work collaboratively with anyone using git, so it's a great learning opportunity for me.

I have now created a "devel" branch locally, where I'll merge all my own changes.  This will mean, as you suggest, that I can easily branch from master next time.
